# Generated by Django 6.0.4 on 2026-05-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vegeterian',
            new_name='vegetarian',
        ),
    ]
