# Generated by Django 6.1 on 2026-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='rest123', max_length=128),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://images.venuebookingz.com/22886-1777034898-wm-triple_eight_bar_(9).jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
